// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package rmp

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// NewSearchNewSearch includes the requested fields of the GraphQL type newSearch.
type NewSearchNewSearch struct {
	// Get Filtered/Sorted Teacher Search Results
	Teachers *NewSearchNewSearchTeachersTeacherSearchConnectionConnection `json:"teachers"`
}

// GetTeachers returns NewSearchNewSearch.Teachers, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearch) GetTeachers() *NewSearchNewSearchTeachersTeacherSearchConnectionConnection {
	return v.Teachers
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnection includes the requested fields of the GraphQL type TeacherSearchConnectionConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type NewSearchNewSearchTeachersTeacherSearchConnectionConnection struct {
	// Information to aid in pagination.
	Edges []*NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdge `json:"edges"`
	// Information to aid in pagination.
	PageInfo NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo `json:"pageInfo"`
}

// GetEdges returns NewSearchNewSearchTeachersTeacherSearchConnectionConnection.Edges, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnection) GetEdges() []*NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdge {
	return v.Edges
}

// GetPageInfo returns NewSearchNewSearchTeachersTeacherSearchConnectionConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnection) GetPageInfo() NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo {
	return v.PageInfo
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdge includes the requested fields of the GraphQL type TeacherSearchConnectionEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection
type NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdge struct {
	// The item at the end of the edge
	Node *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher `json:"node"`
}

// GetNode returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdge.Node, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdge) GetNode() *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher {
	return v.Node
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher includes the requested fields of the GraphQL type Teacher.
type NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher struct {
	Id        *string                                                                                                                        `json:"id"`
	FirstName *string                                                                                                                        `json:"firstName"`
	LastName  *string                                                                                                                        `json:"lastName"`
	Ratings   *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnection `json:"ratings"`
}

// GetId returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher.Id, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher) GetId() *string {
	return v.Id
}

// GetFirstName returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher.FirstName, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher) GetFirstName() *string {
	return v.FirstName
}

// GetLastName returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher.LastName, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher) GetLastName() *string {
	return v.LastName
}

// GetRatings returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher.Ratings, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacher) GetRatings() *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnection {
	return v.Ratings
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnection includes the requested fields of the GraphQL type RatingConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnection struct {
	// Information to aid in pagination.
	Edges []*NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdge `json:"edges"`
}

// GetEdges returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnection.Edges, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnection) GetEdges() []*NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdge {
	return v.Edges
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdge includes the requested fields of the GraphQL type RatingEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection
type NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdge struct {
	// The item at the end of the edge
	Node *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating `json:"node"`
}

// GetNode returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdge.Node, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdge) GetNode() *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating {
	return v.Node
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating includes the requested fields of the GraphQL type Rating.
type NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating struct {
	// An average of helpfulRating and clarityRating
	QualityRating           *int     `json:"qualityRating"`
	DifficultyRatingRounded *float64 `json:"difficultyRatingRounded"`
	Date                    *string  `json:"date"`
	RatingTags              *string  `json:"ratingTags"`
	Grade                   *string  `json:"grade"`
}

// GetQualityRating returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating.QualityRating, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating) GetQualityRating() *int {
	return v.QualityRating
}

// GetDifficultyRatingRounded returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating.DifficultyRatingRounded, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating) GetDifficultyRatingRounded() *float64 {
	return v.DifficultyRatingRounded
}

// GetDate returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating.Date, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating) GetDate() *string {
	return v.Date
}

// GetRatingTags returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating.RatingTags, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating) GetRatingTags() *string {
	return v.RatingTags
}

// GetGrade returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating.Grade, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionEdgesTeacherSearchConnectionEdgeNodeTeacherRatingsRatingConnectionEdgesRatingEdgeNodeRating) GetGrade() *string {
	return v.Grade
}

// NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *NewSearchNewSearchTeachersTeacherSearchConnectionConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// NewSearchResponse is returned by NewSearch on success.
type NewSearchResponse struct {
	// Get New Search Results
	NewSearch *NewSearchNewSearch `json:"newSearch"`
}

// GetNewSearch returns NewSearchResponse.NewSearch, and is useful for accessing the field via an interface.
func (v *NewSearchResponse) GetNewSearch() *NewSearchNewSearch { return v.NewSearch }

// __NewSearchInput is used internally by genqlient
type __NewSearchInput struct {
	SchoolId *string `json:"schoolId"`
	First    int     `json:"first"`
	Cursor   string  `json:"cursor"`
}

// GetSchoolId returns __NewSearchInput.SchoolId, and is useful for accessing the field via an interface.
func (v *__NewSearchInput) GetSchoolId() *string { return v.SchoolId }

// GetFirst returns __NewSearchInput.First, and is useful for accessing the field via an interface.
func (v *__NewSearchInput) GetFirst() int { return v.First }

// GetCursor returns __NewSearchInput.Cursor, and is useful for accessing the field via an interface.
func (v *__NewSearchInput) GetCursor() string { return v.Cursor }

func NewSearch(
	ctx context.Context,
	client graphql.Client,
	schoolId *string,
	first int,
	cursor string,
) (*NewSearchResponse, error) {
	req := &graphql.Request{
		OpName: "NewSearch",
		Query: `
query NewSearch ($schoolId: ID, $first: Int!, $cursor: String!) {
	newSearch {
		teachers(query: {text:"",schoolID:$schoolId}, first: $first, after: $cursor) {
			edges {
				node {
					id
					firstName
					lastName
					ratings(first: 500) {
						edges {
							node {
								qualityRating
								difficultyRatingRounded
								date
								ratingTags
								grade
							}
						}
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`,
		Variables: &__NewSearchInput{
			SchoolId: schoolId,
			First:    first,
			Cursor:   cursor,
		},
	}
	var err error

	var data NewSearchResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
